name = "FinalProject"
version = "0.1.0"
defaultTargets = ["finalproject"]

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "FinalProject"

[[lean_exe]]
name = "finalproject"
root = "Main"
