name = "FinalProject"
version = "0.1.0"
defaultTargets = ["finalproject"]

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[lean_exe]]
name = "finalproject"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0-rc2"

[[require]]
name = "leanblueprint"
git = "https://github.com/PatrickMassot/leanblueprint"